"""empty message

Revision ID: 2906f2ebad82
Revises: 69405d8862f2
Create Date: 2024-07-20 20:55:36.300645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2906f2ebad82'
down_revision = '69405d8862f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites_relation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_relation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='favorites_relation_character_id_fkey'),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], name='favorites_relation_favorite_id_fkey'),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='favorites_relation_planet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_relation_pkey')
    )
    # ### end Alembic commands ###
