"""empty message

Revision ID: 2a66e8e3be6d
Revises: f04dbd0b798a
Create Date: 2024-07-19 20:38:34.365825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a66e8e3be6d'
down_revision = 'f04dbd0b798a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_favorite_id_fkey', type_='foreignkey')
        batch_op.drop_column('favorite_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('character_favorite_id_fkey', 'favorite', ['favorite_id'], ['id'])

    # ### end Alembic commands ###
