"""empty message

Revision ID: 69405d8862f2
Revises: 4b354ceeb908
Create Date: 2024-07-20 20:45:22.882182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69405d8862f2'
down_revision = '4b354ceeb908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorite_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_favorite_id_fkey', type_='foreignkey')
        batch_op.drop_column('favorite_id')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint('planet_favorite_id_fkey', type_='foreignkey')
        batch_op.drop_column('favorite_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('planet_favorite_id_fkey', 'favorite', ['favorite_id'], ['id'])

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('character_favorite_id_fkey', 'favorite', ['favorite_id'], ['id'])

    op.drop_table('favorites_relation')
    # ### end Alembic commands ###
