"""empty message

Revision ID: 79088a51f8b7
Revises: aa2b99885974
Create Date: 2024-07-20 00:01:01.346440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79088a51f8b7'
down_revision = 'aa2b99885974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
