"""empty message

Revision ID: 81047884a96a
Revises: 41b11c5e24f5
Create Date: 2024-07-24 23:21:07.060652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81047884a96a'
down_revision = '41b11c5e24f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
