"""empty message

Revision ID: ad0ecbd33b3e
Revises: 79088a51f8b7
Create Date: 2024-07-20 00:58:42.785129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0ecbd33b3e'
down_revision = '79088a51f8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_character',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], ),
    sa.PrimaryKeyConstraint('favorite_id', 'character_id')
    )
    op.create_table('favorite_planet',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('favorite_id', 'planet_id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_favorite_id_fkey', type_='foreignkey')
        batch_op.drop_column('favorite_id')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint('planet_favorite_id_fkey', type_='foreignkey')
        batch_op.drop_column('favorite_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('planet_favorite_id_fkey', 'favorite', ['favorite_id'], ['id'])

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('character_favorite_id_fkey', 'favorite', ['favorite_id'], ['id'])

    op.drop_table('favorite_planet')
    op.drop_table('favorite_character')
    # ### end Alembic commands ###
